---
- name: Configure local workstation
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    include_deprecated: "false"
  pre_tasks:
    - name: Populate variables
      ansible.builtin.include_vars:
        dir: ansible/vars
        ignore_unknown_extensions: true
        extensions:
          - ""
          - "yaml"
          - "yml"
          - "json"
      tags:
        - always

    - name: "Ensure system-wide directory exist"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        recurse: true
      become: true
      loop:
        - "/usr/local/bin"
      tags:
        - always

    - name: "Ensure directory exist"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        recurse: true
      loop:
        - "{{ localbin_dir }}"
        - "{{ gitconfig_dir }}"
        - "{{ gitconfig_dir }}/cmd"
        - "{{ fonts_dir }}"
        - "{{ gnupg_dir }}"
        - "{{ ssh_dir }}"
      tags:
        - always

  tasks:
    - name: Common Installation for Debian (Ubuntu)
      ansible.builtin.include_tasks: ansible/common.debian.yaml
      when: ansible_system == "Linux" and ansible_os_family == "Debian"
      tags:
        - common

    - name: Common Installation for Darwin (OSX)
      ansible.builtin.include_tasks: ansible/common.darwin.yaml
      when: ansible_system == "Darwin"
      tags:
        - common

    - name: Common Installation
      ansible.builtin.include_tasks: ansible/common.yaml
      tags:
        - common

    - name: Configure Fonts
      ansible.builtin.include_tasks: ansible/fonts.yaml
      tags:
        - fonts

    - name: Configure Programming Language
      ansible.builtin.include_tasks: ansible/languages.yaml
      tags:
        - proglang

    - name: Configure Kubectl
      ansible.builtin.include_tasks: ansible/kubectl.yaml
      tags:
        - kubectl

    - name: Configure ZSH Shell
      ansible.builtin.include_tasks: ansible/zsh.yaml
      tags:
        - zsh

    - name: Configure Toolkit
      ansible.builtin.include_tasks: ansible/toolkit.yaml
      tags:
        - toolkit

    - name: "[Deprecated] Configure Additional Toolkit"
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - ansible/deprecated/*.yaml
      tags:
        - deprecated
      when: include_deprecated | bool

    - name: "Post installation"
      ansible.builtin.debug:
        msg: "{{ post_install.split('\n') }}"
      tags:
        - common
