- name: Download personal dotfiles
  ansible.builtin.git:
    repo: "https://github.com/ardikabs/dotfiles.git"
    dest: /tmp/dotfiles
    version: main
    update: true
    force: true
  tags:
    - common
    - dotfiles

- name: Download asdf plugins
  ansible.builtin.shell: "asdf plugin add {{ item.name }} {{ item.repo | default() }}"
  args:
    executable: /bin/zsh
  loop: "{{ asdf_plugins }}"
  failed_when: dl_asdf_plugin.rc == 1
  changed_when: dl_asdf_plugin.stderr == ""
  register: dl_asdf_plugin
  tags:
    - common
    - asdf

- name: Install asdf plugins
  ansible.builtin.shell: "asdf install {{ item.0.name }} {{ item.1 }}"
  args:
    executable: /bin/zsh
  loop: "{{ asdf_plugins | subelements('versions') }}"
  changed_when: "'installed' not in install_asdf_plugin.stdout"
  register: install_asdf_plugin
  tags:
    - common
    - asdf

- name: Set global asdf plugins
  ansible.builtin.shell: "asdf global {{ item.name }} {{ item.global }}"
  args:
    executable: /bin/zsh
  changed_when: true
  loop: "{{ asdf_plugins }}"
  tags:
    - common
    - asdf
